# Generated by Django 2.0.2 on 2018-10-19 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=20, null=True, verbose_name='项目描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('stock', models.PositiveIntegerField(verbose_name='库存')),
            ],
            options={
                'verbose_name': '购买项目',
                'verbose_name_plural': '购买项目',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='照片')),
            ],
            options={
                'verbose_name': '商品照片',
                'verbose_name_plural': '商品照片',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='名称')),
                ('image', models.ImageField(upload_to='products/', verbose_name='照片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('nutrition', models.TextField(blank=True, null=True, verbose_name='营养成分')),
                ('effect', models.TextField(blank=True, null=True, verbose_name='用途功效')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='上架时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.Product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Product', verbose_name='商品'),
        ),
    ]
